export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <header style={{
          backgroundColor: "lightblue",
          padding: "1rem"
        }}>
          <p>Header</p>

        </header>

        {children}

        <footer
          style={{
            backgroundColor: "lightgreen",
            padding: "1rem",
            position:"fixed",
            bottom: "0",
            width:"100%"
          }}>

          <h1>All rights are recived from abcd@2025</h1>
        </footer>

      </body>
    </html>
  )
}
